// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciodbefnipqsohdwrmcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpb2RiZWZuaXBxc29oZHdybWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzA1MjQsImV4cCI6MjA3MzEwNjUyNH0.BZnJqA2tGUH3n8568NU-lkKj5vF0Cx5Sr1cuhnOf6bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});